name: number_trivia
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.1.3
  # Bloc for state management
  flutter_bloc: ^7.0.0
  bloc_test: ^8.0.0
  # Value equality
  equatable: ^2.0.0
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.3
  # Local cache
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7